-- Blame Opal — Leaderboard schema
-- Run this once inside Supabase → SQL Editor → New query → paste → Run.
-- Safe to re-run (uses IF NOT EXISTS and creates policies idempotently).

-- 1. Scores table
create table if not exists public.scores (
  id          bigint generated by default as identity primary key,
  name        text        not null check (char_length(name) between 1 and 5),
  score       integer     not null check (score >= 0 and score <= 1000000),
  level       integer     not null check (level >= 1 and level <= 100),
  created_at  timestamptz not null default now()
);

-- 2. Index for fast monthly top-10 queries
create index if not exists scores_leaderboard_idx
  on public.scores (created_at desc, score desc);

-- 3. Lock the table down with Row Level Security
alter table public.scores enable row level security;

-- 4. Anyone can read all scores
drop policy if exists "scores_select_all" on public.scores;
create policy "scores_select_all"
  on public.scores
  for select
  to anon, authenticated
  using (true);

-- 5. Anyone can insert a new score (no update / no delete allowed)
drop policy if exists "scores_insert_anon" on public.scores;
create policy "scores_insert_anon"
  on public.scores
  for insert
  to anon, authenticated
  with check (
    char_length(name) between 1 and 5
    and score between 0 and 1000000
    and level between 1 and 100
  );

-- That's it. The leaderboard query already filters to "current month",
-- so a monthly reset happens automatically on the 1st of each month with no cron job needed.
